name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    # The HACS action cannot currently read manifest files from private repositories.
    # This check starts running automatically if the repository is made public.
    if: ${{ github.event.repository.private == false }}
    runs-on: ubuntu-latest
    steps:
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          comment: false

  hassfest:
    name: Home Assistant hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Validate integration
        uses: home-assistant/actions/hassfest@master
